### PR TITLE
Update to std@v0.50.0 and fix tests

### LINKED ISSUE #3: Namespace 'Deno' has no exported member 'EOF'.
Hey, great job with the library! But I'm having this error just by importing the library:

```ts
import { expect } from "https://deno.land/x/expect/expect.ts"
```

```
deno run -c tsconfig.json ioc_tests.ts                                                                          vie  8 may 21:35:33 2020
Compile file:///Users/danielramos/Documents/Repos/Trabajo/AcidTango/Interno/boilerplates/deno-ddd/ioc_tests.ts
error TS2694: Namespace 'Deno' has no exported member 'EOF'.
export function assertNotEOF<T extends {}>(val: T | Deno.EOF): T {
                                                         ~~~
    at https://deno.land/std@v0.41.0/testing/asserts.ts:383:58

error TS2339: Property 'EOF' does not exist on type 'typeof Deno'.
  assertNotEquals(val, Deno.EOF);
                            ~~~
    at https://deno.land/std@v0.41.0/testing/asserts.ts:384:29

Found 2 errors.

```

Deno & TS version
```
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
```

### PR DESCRIPTION
**Pull request by DanielRamosAcosta**
This PR upgrades from `std@v0.41.0` to `std@v0.50.0`, which works on Deno `1.0.0-rc1`. The interface of the tests have changed, it also fixes that.

Fixes #3

### CODE REVIEW

**Comment by allain** [comment]
Thanks!
